version: "3.7"
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    volumes:
      - /docker/nginx/etc/nginx:/etc/nginx
      - /docker/nginx/etc/letsencrypt:/etc/letsencrypt
    environment:
      DOMAIN_NAME: www.example.com
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - bookstack

  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=https://www.example.com
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=35ws46edtufdfs211
      - DB_DATABASE=bookstackapp
    volumes:
      - /docker/bookstack/config:/config
#    ports:
#      - 6875:80
    restart: always
    depends_on:
      - bookstack_db
  bookstack_db:

    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=35ws46edtufdfs211
      - TZ=America/Sao_Paulo
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=35ws46edtufdfs211
    volumes:
      - /docker/bookstack_db/config:/config
    restart: always